# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode11.1
env:
  matrix:
    - TEST_SDK=iphonesimulator13.1 OS=13.1 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator13.1 OS=13.1 NAME='iPhone 8'

script:
  - set -o pipefail

