# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: swift
script:
- set -o pipefail

after_success:
  - bash <(curl -s https://codecov.io/bash)