# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode10.2.1
env:
  matrix:
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone 8'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/MBHealthTracker.xcworkspace -scheme MBHealthTracker-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty

